minecraft_version=26.1

# Mod
mod_id=camellia
mod_name=Camellia
mod_version=1.0.0
mod_group=me.lilac.camellia
mod_license=WTFPL
mod_authors=Lilac
mod_description=Example mod for Camellia Config

# Fabric
loader_version=0.18.5
maven_group=me.lilac
archives_base_name=camellia-fabric
fabric_version=0.144.3+26.1
loom_version=1.15-SNAPSHOT

# Integrations
modmenu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true